/**
 * Template engine for PR body generation
 * Supports Handlebars-style templates with workflow variables
 */

import Handlebars from 'handlebars';
import { existsSync, readFileSync } from 'fs';
import { join } from 'path';
import { z } from 'zod';
import type { WorkflowContext } from '../core/types.js';
import { createLogger } from '../utils/logger.js';
import { toError } from '../utils/error-handlers.js';
import { formatDuration, formatDurationHuman } from '../utils/formatting.js';
import { PR_AUTOMATION_DEFAULTS } from './constants.js';
import {
  getPackageDefaultDir,
  getGlobalConfigDir,
  getProjectConfigDir,
} from '../utils/paths.js';
import { loadSettings, type ResolvedSettings } from '../utils/settings.js';

/**
 * Zod schema for validating stage result structure
 * Aligns with ExecutionResult type where metrics is required
 */
const StageResultSchema = z.object({
  success: z.boolean().optional(),
  metrics: z.object({
    tokensUsed: z.number().optional(),
    cost: z.number().optional(),
    duration: z.number().optional(),
    provider: z.string().optional(),
  }),
});

const logger = createLogger('template-engine');

/**
 * PR template filename (used across all config locations)
 */
const TEMPLATE_FILENAME = 'github_pull_request_template.md';

/**
 * Minimal fallback template used when no template file is found
 */
const MINIMAL_FALLBACK_TEMPLATE = `## Summary

{{taskDescription}}

---

[![AIRunX Powered](https://img.shields.io/badge/AIRunX-Powered-black?style=flat-square&labelColor=1E3A8A)](https://github.com/digitalpyro/airunx) _Generated by AIRunX_`;

/**
 * Stage performance entry for template rendering
 */
export interface StagePerformanceEntry {
  name: string;
  provider?: string;
  tokens: string;
  cost: string;
  runtime: string;
  status: string;
}

/**
 * Provider breakdown entry for template rendering
 */
export interface ProviderBreakdownEntry {
  provider: string;
  stages: number;
  tokens: string;
  cost: string;
}

/**
 * Template context variables available for substitution
 */
export interface TemplateContext {
  taskDescription: string;
  taskTitle: string;
  fidelityLevel: string;
  backend: string;
  iterationCount: number;
  maxIterations: number;
  runtime: string;
  totalTokens: string;
  totalCost: string;
  todos: string;
  testCommands: string;
  /** Custom test plan provided by agent (if available) */
  testPlan?: string;
  /** Stage performance data for {{#each}} rendering */
  stagePerformance?: StagePerformanceEntry[];
  /** Whether any stage has provider info (controls Provider column visibility) */
  hasProviderInfo?: boolean;
  iterationHistory?: string;
  /** Per-provider cost breakdown for multi-provider workflows */
  providerBreakdown?: ProviderBreakdownEntry[];
  /** Whether to include airunx signature badge */
  airunxSignature?: boolean;
}

/**
 * TemplateEngine handles PR body template loading and rendering
 * Uses memoization to cache compiled templates for performance
 */
export class TemplateEngine {
  // Cache for compiled templates (keyed by repoPath or 'default')
  private templateCache = new Map<string, Handlebars.TemplateDelegate>();

  /**
   * Clear the template cache (useful for testing)
   */
  clearCache(): void {
    this.templateCache.clear();
    logger.debug('Template cache cleared');
  }

  /**
   * Load and compile template using config hierarchy
   *
   * Priority (highest to lowest):
   * 1. Project: .airunx/github_pull_request_template.md
   * 2. Global: ~/.airunx/github_pull_request_template.md
   * 3. Default: config/default/github_pull_request_template.md
   */
  private loadTemplate(repoPath?: string): Handlebars.TemplateDelegate {
    const cacheKey = repoPath || 'default';

    // Return cached template if available
    const cached = this.templateCache.get(cacheKey);
    if (cached) {
      return cached;
    }

    // Define template locations in priority order
    const templateLocations = [
      {
        type: 'project',
        path: repoPath
          ? join(getProjectConfigDir(repoPath), TEMPLATE_FILENAME)
          : null,
      },
      {
        type: 'global',
        path: join(getGlobalConfigDir(), TEMPLATE_FILENAME),
      },
      {
        type: 'default',
        path: join(getPackageDefaultDir(), TEMPLATE_FILENAME),
      },
    ];

    let templateSource: string | null = null;

    // Try each location in priority order
    for (const location of templateLocations) {
      if (location.path && existsSync(location.path)) {
        try {
          templateSource = readFileSync(location.path, 'utf-8');
          logger.info(
            location.type === 'default'
              ? 'Using default PR template'
              : `Loaded PR template from ${location.type}: ${location.path}`
          );
          break;
        } catch (error) {
          logger.warn(
            `Failed to load ${location.type} template: ${toError(error).message}`
          );
        }
      }
    }

    // Final fallback: minimal template
    if (!templateSource) {
      logger.warn('No PR template found, using minimal fallback');
      templateSource = MINIMAL_FALLBACK_TEMPLATE;
    }

    // Compile template
    let compiled: Handlebars.TemplateDelegate;
    try {
      compiled = Handlebars.compile(templateSource);
    } catch (error) {
      logger.error(`Template compilation failed: ${toError(error).message}`);
      compiled = Handlebars.compile(MINIMAL_FALLBACK_TEMPLATE);
    }

    // Cache and return
    this.templateCache.set(cacheKey, compiled);
    return compiled;
  }

  /**
   * Render PR body from workflow context
   */
  async render(context: WorkflowContext): Promise<string> {
    // Always load template for the given context (stateless)
    const compiledTemplate = this.loadTemplate(context.repoPath);

    // Load settings once at render level for dependency injection
    const settings = loadSettings(context.repoPath);
    const templateContext = this.buildContext(context, settings);

    try {
      let body = compiledTemplate(templateContext);

      // Prepend Closes link if issue URL is available (enables cross-repo issue closing)
      if (context.issueUrl) {
        body = `Closes ${context.issueUrl}\n\n${body}`;
      }

      return body;
    } catch (error) {
      logger.error(`Template rendering failed: ${toError(error).message}`);
      // Fallback to minimal output
      return this.renderMinimal(context);
    }
  }

  /**
   * Detect appropriate test commands based on project type
   */
  private detectTestCommands(repoPath?: string): string {
    if (!repoPath) {
      return '# Run your project-specific test command';
    }

    // Check for common project type indicators
    const checks: Array<{ file: string; command: string }> = [
      // Ruby/Rails
      { file: 'Gemfile', command: 'bundle exec rails test' },
      { file: 'Rakefile', command: 'bundle exec rake test' },
      // Python
      { file: 'pyproject.toml', command: 'pytest' },
      { file: 'setup.py', command: 'pytest' },
      { file: 'requirements.txt', command: 'pytest' },
      // PHP
      { file: 'composer.json', command: 'composer test' },
      // Go
      { file: 'go.mod', command: 'go test ./...' },
      // Rust
      { file: 'Cargo.toml', command: 'cargo test' },
      // Node.js (last since package.json is common)
      { file: 'package.json', command: 'npm test' },
    ];

    for (const { file, command } of checks) {
      if (existsSync(join(repoPath, file))) {
        return command;
      }
    }

    // No recognized project type - prompt manual verification
    return '# Run your project-specific test command';
  }

  /**
   * Build template context from workflow context
   */
  private buildContext(
    context: WorkflowContext,
    settings: ResolvedSettings
  ): TemplateContext {
    const completedTodos =
      context.todos?.filter((t) => t.status === 'completed') || [];

    const todosMarkdown =
      completedTodos.length > 0
        ? completedTodos.map((t) => `- [x] ${t.title}`).join('\n')
        : '_No todos tracked_';

    return {
      taskDescription:
        context.taskDescription ||
        context.taskTitle ||
        'No description provided',
      taskTitle: context.taskTitle || PR_AUTOMATION_DEFAULTS.TASK_TITLE,
      fidelityLevel:
        context.fidelityLevel || PR_AUTOMATION_DEFAULTS.FIDELITY_LEVEL,
      backend: context.backend || PR_AUTOMATION_DEFAULTS.BACKEND,
      iterationCount: context.iterationCount || 0,
      maxIterations:
        context.maxIterations || PR_AUTOMATION_DEFAULTS.MAX_ITERATIONS,
      runtime: formatDuration(context.metrics?.totalRuntimeMs || 0),
      totalTokens: (context.metrics?.totalTokens || 0).toLocaleString(),
      totalCost: (context.metrics?.totalCost || 0).toFixed(2),
      todos: todosMarkdown,
      testCommands: this.detectTestCommands(context.repoPath),
      testPlan: context.testPlan,
      stagePerformance: this.buildStagePerformance(context),
      hasProviderInfo: this.hasProviderInfo(context),
      iterationHistory: this.buildIterationHistory(context),
      providerBreakdown: this.buildProviderBreakdown(context),
      airunxSignature: settings.airunx_signature,
    };
  }

  /**
   * Type guard to validate stage result structure using Zod schema
   * Stage results are ExecutionResult objects with metrics nested inside
   */
  private isValidStageResult(
    value: unknown
  ): value is z.infer<typeof StageResultSchema> {
    return StageResultSchema.safeParse(value).success;
  }

  /**
   * Check if any stage has provider info
   */
  private hasProviderInfo(context: WorkflowContext): boolean {
    if (!context.stageResults) {
      return false;
    }
    return Object.values(context.stageResults).some(
      (result) =>
        this.isValidStageResult(result) &&
        result.metrics?.provider !== undefined
    );
  }

  /**
   * Build stage performance data as array for {{#each}} template rendering
   */
  private buildStagePerformance(
    context: WorkflowContext
  ): StagePerformanceEntry[] {
    if (
      !context.stageResults ||
      Object.keys(context.stageResults).length === 0
    ) {
      return [];
    }

    const entries: StagePerformanceEntry[] = [];

    for (const [stage, result] of Object.entries(context.stageResults)) {
      if (!this.isValidStageResult(result)) {
        logger.warn(`Skipping invalid stage result for: ${stage}`);
        continue;
      }
      const metrics = result.metrics;
      entries.push({
        name: stage,
        provider: metrics.provider,
        tokens: (metrics.tokensUsed || 0).toLocaleString(),
        cost: (metrics.cost || 0).toFixed(2),
        runtime: formatDurationHuman(metrics.duration || 0),
        status: result.success !== false ? '✅' : '❌',
      });
    }

    return entries;
  }

  /**
   * Build iteration history section
   */
  private buildIterationHistory(context: WorkflowContext): string {
    const entries = context.iterationHistory?.entries;
    if (!entries || entries.length === 0) {
      if (!context.iterationCount || context.iterationCount <= 1) {
        return '';
      }
      return `_Completed in ${context.iterationCount} iteration(s)_`;
    }

    // Build per-iteration breakdown table
    const rows = entries.map((entry) => {
      const tokens =
        entry.tokensUsed != null ? entry.tokensUsed.toLocaleString() : '—';
      const cost = entry.costUsd != null ? `$${entry.costUsd.toFixed(2)}` : '—';
      const gaps = entry.gaps.length > 0 ? entry.gaps.join('; ') : '—';
      return `| ${entry.iteration} | ${entry.verdict} | ${tokens} | ${cost} | ${gaps} |`;
    });

    return [
      `_Completed in ${entries.length} iteration(s)_\n`,
      '| Iteration | Verdict | Tokens | Cost | Gaps |',
      '|-----------|---------|--------|------|------|',
      ...rows,
    ].join('\n');
  }

  /**
   * Build per-provider cost breakdown as array for {{#each}} template rendering
   * Aggregates tokens and cost by provider across all stages
   * Only returns data if multiple providers were used
   */
  private buildProviderBreakdown(
    context: WorkflowContext
  ): ProviderBreakdownEntry[] {
    if (
      !context.stageResults ||
      Object.keys(context.stageResults).length === 0
    ) {
      return [];
    }

    // Aggregate metrics by provider
    const providerStats = new Map<
      string,
      { tokens: number; cost: number; stages: number }
    >();

    for (const result of Object.values(context.stageResults)) {
      if (!this.isValidStageResult(result)) {
        continue;
      }
      const metrics = result.metrics;
      const provider = metrics.provider?.trim() || 'unknown';

      // Update or initialize provider stats (atomic update)
      const currentStats = providerStats.get(provider) ?? {
        tokens: 0,
        cost: 0,
        stages: 0,
      };
      providerStats.set(provider, {
        tokens: currentStats.tokens + (metrics.tokensUsed || 0),
        cost: currentStats.cost + (metrics.cost || 0),
        stages: currentStats.stages + 1,
      });
    }

    // Only show breakdown if multiple providers were used
    if (providerStats.size <= 1) {
      return [];
    }

    // Sort by cost descending and convert to array
    const sorted = [...providerStats.entries()].sort(
      ([, a], [, b]) => b.cost - a.cost
    );

    return sorted.map(([provider, stats]) => ({
      provider,
      stages: stats.stages,
      tokens: stats.tokens.toLocaleString(),
      cost: stats.cost.toFixed(2),
    }));
  }

  /**
   * Render minimal PR body as fallback
   */
  private renderMinimal(context: WorkflowContext): string {
    const closesLink = context.issueUrl ? `Closes ${context.issueUrl}\n\n` : '';

    return `${closesLink}## ${context.taskTitle || 'AI-Generated Implementation'}

${context.taskDescription || 'No description provided'}

---

[![AIRunX Powered](https://img.shields.io/badge/AIRunX-Powered-black?style=flat-square&labelColor=1E3A8A)](https://github.com/digitalpyro/airunx) **Generated by AIRunX**
- Fidelity: ${context.fidelityLevel || 'standard'}
- Backend: ${context.backend || 'claude-code'}
`;
  }

  /**
   * Get the default template content (for testing)
   */
  getDefaultTemplate(): string {
    const defaultPath = join(getPackageDefaultDir(), TEMPLATE_FILENAME);
    if (existsSync(defaultPath)) {
      return readFileSync(defaultPath, 'utf-8');
    }
    return MINIMAL_FALLBACK_TEMPLATE;
  }
}
